name: Purge jsDelivr CDN Cache

on:
  schedule:
    # 使用 cron 表达式定义每5小时运行一次
    - cron: "0 */5 * * *"

jobs:
  purge-cdn:
    runs-on: ubuntu-latest

    steps:
      - name: Purge Cache
        run: |
          curl -X PURGE https://purge.jsdelivr.net/gh/${{ github.repository }}
